---
# Steps
# =======
# - Provision *** take that out ***
# - Validate the nodes
# - Bootstrap: Prepare the slaves
# - Configure packstack answer-file
#       - apply rdo config
#       - apply multinode config
# - Deploy Openstack using packstack
# - Reboot all test-vms
# - Tempest slave
# - Run tempest [task]
# - Collect logs
# - CleanUp
#

### enable to provison vm
- include: ../dump_settings.yml
- include: ../provision.yml
- include: ../group_by.yml tags=provision
- include: multinode/provision.yml

- include: ../validate_nodes.yml

- name: Gather facts from all openstack hosts
  hosts: all:!localhost:!tempest
  tags:
    - provision

- name: Debug list config variables
  hosts: local
  sudo: no
  roles:
    - { role: packstack/debug }
  tags:
    - provision

- include: multinode/setup-ssh-keys.yml tags=prep

- name: Prepare system for packstack
  hosts: packstack
  roles:
    - { role: common }
    - { role: linux-common }
  tags:
    - prep

# apply pre-packstack workarouds
- include: ../../workarounds/workarounds-prep.yml tags=workaround

- name: Group hosts by product rdo/rhos
  hosts: all:!localhost:!tempest
  tasks:
    - group_by: key={{ config.product }}
  tags:
    - prep

- name: Setup packstack on Controller
  hosts: controller:&rhos
  roles:
      - packstack/rhos
  tags: prep

- name: Setup packstack on Controller
  hosts: controller:&rdo
  roles:
      - packstack/rdo
  tags: prep

- name: Setup multinode packstack answerfile
  hosts: controller
  roles:
      - packstack/multinode
  tags: prep

- include: ../../workarounds/workarounds-pre-run-packstack.yml tags=workaround

- name: Run packstack
  hosts: controller
  roles:
    - { role: packstack/runner }
  tags: run-packstack

- include: ../../workarounds/workarounds-post-run-packstack.yml tags=workaround

- name: Config ml2-plugin
  hosts: controller
  roles:
    - role: packstack/neutron/ml2-plugin
  tags: ml2-plugin

- name: Get Status after reboot
  hosts: controller
  roles:
    - { role: openstack/openstack-status }
  tags:
    - run-packstack

- include: tempest.yml

- name: SELINUX error check
  hosts: all:!localhost:!tempest
  roles:
    - { role: selinux_check }
  tags:
    - provision
