- name: Group hosts by post action - update
  hosts: undercloud:overcloud
  gather_facts: no
  tasks:
    - group_by: key="update"
      when: installer.updates is defined and
            installer.updates.enabled|bool

- name: Update the Undercloud
  gather_facts: no
  hosts: update:!overcloud
  tasks:
    - name: repolist
      sudo: yes
      command: yum -d 7 repolist

    - name: get neutron debug info
      register: neutron_port_list_output
      shell: >
          source {{ instack_user_home }}/stackrc;
          neutron port-list;

    - name: get openstack-tripleo-heat-template version
      register: openstack-tripleo-heat-template_version
      shell: >
          rpm -qa | grep openstack-tripleo-heat-template

    - name: update packages
      sudo: yes
      register: yum_update_result
      yum: name=* state=latest

    - name: fail when no package has been updated
      fail: msg="Failed, no package has been updated on the undercloud"
      when: not yum_update_result.changed|bool

    - name: reboot host
      local_action:
        wait_for_ssh
          reboot_first=true
          host="{{ ansible_ssh_host }}"
          user="stack"
          ssh_opts="-F {{ base_dir }}/khaleesi/ssh.config.ansible"
          key="{{ ansible_ssh_private_key_file }}"
          timeout=900
          sudo=true

    - name: create vlan10 if doesn't exist
      ignore_errors: yes
      sudo: yes
      shell: >
        ifconfig vlan10;
        if [[ $? != 0 ]]; then \
        ovs-vsctl add-port br-ctlplane vlan10 tag=10 -- set interface vlan10 \
        type=internal; fi
      when: installer.network.isolation == 'single_nic_vlans'

    - name: set vlan up
      ignore_errors: yes
      sudo: yes
      shell: >
        ip l set dev vlan10 up; ip addr add 172.16.23.251/24 dev vlan10;
      when: installer.network.isolation == 'single_nic_vlans'
