- name: rpm | repo used
  debug: msg="using tempest repo {{ tempest_rpm_repo }}" #"
  tags: tempest_setup_rpm
  when: tempest.use_custom_repo|bool

- name: rpm | create the tempest Repository
  template: src=tempest.repo.j2 dest=/etc/yum.repos.d/tempest.repo
  sudo: yes
  tags:
    - tempest_setup_rpm
  when: tempest.use_custom_repo|bool
  notify:
    - Yum clean all
    - Yum repolist

- meta: flush_handlers

- name: rpm | install tempest rpm
  yum: name=openstack-tempest-{{ tempest.rdo.version }}-{{ tempest.rpm.version }} state=present
  sudo: yes
  tags: tempest_setup_rpm

- debug: msg="{{ tempest.dir }}"
  tags: tempest_setup_rpm

- name: rpm | create tempest.dir
  file: path="{{ tempest.dir }}" state=directory

- name: config_tempest | setup user directory to run tempest
  command: "/usr/share/openstack-tempest-{{ tempest.rdo.version }}/tools/configure-tempest-directory
           /usr/share/openstack-tempest-{{ tempest.rdo.version }}
           chdir={{ tempest.dir }}"

- include: generate-tempest-havana-conf.yml
  when: ("{{ product.version }}" == "havana") or ("{{ product.version }}" == "4.0")

- include: generate-tempest-non-havana-conf.yml
  when: ("{{ product.version }}" != "havana") and ("{{ product.version }}" != "4.0")
