---
  - name: Remove the EPEL Repository.
    yum: name=epel-release state=removed
    when: ansible_distribution == "RedHat"

  - name: Yum clean all
    command: yum clean all
    when: ansible_distribution == "RedHat"

  - name: create ssh keys
    shell: ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa creates=/root/.ssh/id_rsa

  - name: add id_rsa to authorized_keys
    shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

  - name: ensure authorized_keys file has correct permissions
    file: path=/root/.ssh/authorized_keys owner=root group=root mode=0600

  - name: ensure iptables is running 
    service: name=iptables state=started
