---
- name: yum remove old rdo-release
  yum: name=rdo-release* state=absent
  ignore_errors: yes

- name: Ensure rdo yum repositories are removed
  file: path=/etc/yum.repos.d/{{ item }} state=absent
  with_items: repos_to_remove
  notify:
    - Yum clean all

 ## for e.g: baseurl={{ rdo.icehouse.production.repo.fedora }} ##
- debug: msg="Setting baseurl to {{ rdo[config.version][config.repo].repo[ansible_distribution][ansible_distribution_version] }}"
  when: config.repo != 'distribution'

- name: Find diff between current repo {{ config.repo }} and production
  shell: repodiff --old={{ repo_production }} --new={{ repo_current }} | tee /var/log/rdo_stage_prod_repo.txt
  register: result
  when:  config.repo != 'production'
  ignore_errors: yes

- name: print diff between current repo {{ config.repo }} and production repo
  debug: var=result.stdout_lines
  when:  config.repo != 'production'

