require 'yaml'

settings = YAML.load_file(ENV['VAGRANT_KHALEESI_SETTINGS'])
servers = settings['staypuft']['nodes']
networks = settings['staypuft']['networks']

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".","/vagrant", disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    # libvirt.host = "localhost"
    # libvirt.connect_via_ssh = true
    # libvirt.username = ENV['USERNAME']
    # libvirt.id_ssh_key_file = ENV['ID_SSH_KEY_FILE'] || 'id_dsa'
    libvirt.uri = "qemu:///system"
  end

  servers.each do |name,server|
    config.vm.define name do |serv|
      serv.vm.box = server['box']
      serv.vm.provider :libvirt do |domain|
        domain.memory = server['memory']
        domain.cpus = server['cpus']
      end
      networks.each do |network|
        if network['public_network']
          serv.vm.network :public_network,
            dev: network['bridge'],
            type: "bridge",
            libvirt__adapter: network['adapter'],
            model_type: 'virtio'
        else
          serv.vm.network :private_network,
            ip: "#{network['prefix']}.#{server['ip_suffix']}",
            libvirt__adapter: network['adapter'],
            libvirt__network_name: network['network_name'],
            libvirt__dhcp_enabled: network['dhcp_enabled'],
            libvirt__forward_mode: network['forward_mode']
        end
      end
      if name == "foreman"
        serv.vm.provision "ansible", run: 'always' do |ansible|
          ansible.verbose = 'vvv'
          ansible.playbook = ENV['VAGRANT_PLAYBOOK']
          ansible.extra_vars = ENV['VAGRANT_KHALEESI_SETTINGS']
          ansible.groups = {
            "staypuft" => ["foreman"]
          }
        end
        serv.vm.network :forwarded_port, guest: 443, host: 443, host_ip: '0.0.0.0'
        serv.vm.network :forwarded_port, guest: 80, host: 80, host_ip: '0.0.0.0'
      else
        serv.vm.boot_timeout = 1200
      end
    end
  end
end

