---
- name: Configure compute nodes
  hosts: compute
  sudo: yes
  tasks:

    - name: set allow_unsafe_interrupts=1
      shell: echo "options vfio_iommu_type1 allow_unsafe_interrupts=1" > /etc/modprobe.d/dist.conf

    - name: disable neutron-openvswitch-agent
      shell: systemctl disable neutron-openvswitch-agent

    - name: Set Host Physical Function (pf) interface
      set_fact: pf_name="{{ provisioner.nodes[inventory_hostname.split('-')|last ].network.interfaces.data.label }}"

    - name: Set grubby
      shell: |
           driver=$(ethtool -i "{{ pf_name }}" |grep driver  | sed 's/driver: //')
           kernel_path=$(grubby --default-kernel);
           grub_params="intel_iommu=on ${driver}.max_vfs=7";
           grubby --update-kernel=${kernel_path} --args="${grub_params}";

    - name: set pci_white_list
      ini_file:
          dest=/etc/nova/nova.conf
          section=DEFAULT
          option=pci_passthrough_whitelist
          value='{"devname":"{{ pf_name }}", "physical_network":"{{ installer.network.internal.label }}"}'

    - name: Install openstack-neutron-sriov-nic-agent
      yum: name=openstack-neutron-sriov-nic-agent state=installed

    - name: Configure openstack-neutron-sriov-nic-agent
      ini_file:
          dest=/etc/neutron/plugins/ml2/sriov_agent.ini
          section=sriov_nic
          option=physical_device_mappings
          value="{{ installer.network.internal.label }}":"{{ pf_name }}"

    - name: Enable neutron-sriov-nic-agent
      service: name=neutron-sriov-nic-agent state=started enabled=yes

    - local_action:
          module: wait_for_ssh reboot_first=true host={{ hostvars[inventory_hostname].ansible_ssh_host }} user={{ hostvars[inventory_hostname].ansible_ssh_user }} key={{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}
      sudo: no
