---
- name: Prepare templates
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  roles:
      - {role: ospd/overcloud/network/isolation/, when: installer.overcloud.network.isolation.enable == "yes"}
      - {role: ospd/overcloud/network/ipv6/, when: installer.overcloud.network.ipv6 == "yes"}
      - {role: ospd/overcloud/ssl/, when: installer.overcloud.use_ssl == "yes"}
      - {role: ospd/overcloud/storage/ceph/, when: provisioner.nodes.ceph is defined}
  tasks:
      #TODO: move this to a role for cinder/LVM
      - name: set a higher LVM size storage template
        sudo: yes
        lineinfile:
            dest: "{{ installer.overcloud.template_base }}/puppet/hieradata/controller.yaml"
            line: "cinder::setup_test_volume::size: '10G'"
        when: groups['ceph'] is not defined

- name: Install the overcloud
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  tasks:
      - name: create the overcloud deploy script
        template:
            src: "templates/overcloud_deploy.sh.j2"
            dest: "~/overcloud_deploy.sh"
            mode: 0755

      - name: the create overcloud script
        shell: "cat ~/overcloud_deploy.sh"

      - name: execute the overcloud deploy script (should take ~30 minutes :) )
        shell: "bash ~/overcloud_deploy.sh"
