---
- name: Prepare system for packstack
  hosts: all:!localhost
  sudo: yes
  roles:
    - { role: common }
  tags:
    - prep

- name: RHEL RHOS prep
  hosts: all:!localhost:&RedHat:&rhos
  sudo: yes
  roles:
    - { role: linux/rhel/rhos }
  tags:
    - prep

- name: RHEL RDO prep
  hosts: all:!localhost:&RedHat:&rdo
  sudo: yes
  roles:
    - { role: linux/rhel/rdo }
  tags:
    - prep

- name: CentOS RDO prep
  hosts: all:!localhost:&CentOS:&rdo
  sudo: yes
  roles:
    - { role: linux/centos }
  tags:
    - prep

- name: Fedora RDO prep
  hosts: all:!localhost:&Fedora:&rdo
  sudo: yes
  roles:
    - { role: linux/fedora }
  tags:
    - prep

- name: Linux common prep
  hosts: all:!localhost
  sudo: yes
  roles:
    - { role: linux-common }
  tags:
    - prep

