---
- name: setup environment vars
  template: src=virt-setup-env.j2 dest=~/virt-setup-env mode=0755

- name: run instack-virt-setup
  register: instack_virt_setup_result
  ignore_errors: yes
  shell: >
    source {{ instack_user_home }}/virt-setup-env;
    instack-virt-setup;

- name: update libvirtd unix_sock_group
  sudo: yes
  lineinfile: dest=/etc/libvirt/libvirtd.conf
                  regexp=^unix_sock_group
                  line='unix_sock_group = "stack"'

- name: restart libvirtd
  service: name=libvirtd state=restarted
  sudo: yes

- name: inspect virsh capabilities
  command: 'virsh capabilities'
  sudo: yes

# workaround for the SATA error RHBZ#1195882
- name: remove libvirt qemu capabilities cache
  command:  rm -Rf  /var/cache/libvirt/qemu/capabilities/
  sudo: yes
  when: "instack_virt_setup_result.rc != 0"

# workaround for the SATA error RHBZ#1195882
- name: restart libvirtd
  service: name=libvirtd state=restarted
  sudo: yes
  when: "instack_virt_setup_result.rc != 0"

- name: inspect virsh capabilities
  command: 'virsh capabilities'
  when: "instack_virt_setup_result.rc != 0"

- name: destroy virbr0 network if present
  command: brctl delbr virbr0
  sudo: yes
  ignore_errors: true

- name: retry run instack-virt-setup
  shell: >
    virsh undefine instack;
    source {{ instack_user_home }}/virt-setup-env;
    instack-virt-setup;
  when: "instack_virt_setup_result.rc != 0"

- name: print out all the VMs
  shell: >
    sudo virsh list --all

